# Generated by Django 2.2.7 on 2019-12-08 04:05

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('Country', models.CharField(max_length=20, verbose_name='区域')),
            ],
            options={
                'verbose_name': '区域',
                'verbose_name_plural': '区域',
                'db_table': 'df_Country',
            },
        ),
        migrations.CreateModel(
            name='GoodsProvinces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('city', models.CharField(max_length=20, verbose_name='城市')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCountry', verbose_name='区域')),
            ],
            options={
                'verbose_name': '省份',
                'verbose_name_plural': '省份',
                'db_table': 'df_Provinces',
            },
        ),
        migrations.CreateModel(
            name='GoodsSKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=20, verbose_name='景区名称')),
                ('desc', models.CharField(max_length=256, verbose_name='景区介绍')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最低价格')),
                ('hightprice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最高价格')),
                ('num', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='浏览人数')),
                ('image', models.ImageField(upload_to='goods', verbose_name='商品缩略图')),
                ('stock', models.IntegerField(default=1, verbose_name='商品库存')),
                ('sales', models.IntegerField(default=0, verbose_name='景点销量')),
                ('ranking', models.SmallIntegerField(default=0, verbose_name='展示顺序')),
                ('css_stays', models.CharField(max_length=20, verbose_name='图片样式')),
                ('status', models.SmallIntegerField(choices=[(0, '下线'), (1, '上线')], default=1, verbose_name='景点状态')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsProvinces', verbose_name='城市名')),
            ],
            options={
                'verbose_name': '景点名称',
                'verbose_name_plural': '景点名称',
                'db_table': 'df_goods_sku',
            },
        ),
        migrations.CreateModel(
            name='GoodsSPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('title', models.CharField(max_length=20, verbose_name='景点标题')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='内容')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSKU', verbose_name='景点名称')),
            ],
            options={
                'verbose_name': '景点内容',
                'verbose_name_plural': '景点内容',
                'db_table': 'df_goods_spu',
            },
        ),
        migrations.CreateModel(
            name='goodsphoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('content', models.ImageField(upload_to='goods', verbose_name='景点组图')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSKU', verbose_name='景点名称')),
            ],
            options={
                'verbose_name': '景点图片',
                'verbose_name_plural': '景点图片',
                'db_table': 'df_goods_spu_photo',
            },
        ),
    ]
